import type { MacroTotals, DemoRecipe } from './types'

interface FoodEntry extends MacroTotals {
  matched: string
}

export const MOCK_DB: Record<string, FoodEntry> = {
  // English
  water:          { matched: 'WATER',                   energy_kcal: 0,   protein_g: 0,    carbs_g: 0,    fat_g: 0    },
  salt:           { matched: 'SALT',                    energy_kcal: 0,   protein_g: 0,    carbs_g: 0,    fat_g: 0    },
  sugar:          { matched: 'SUGAR',                   energy_kcal: 387, protein_g: 0,    carbs_g: 100,  fat_g: 0    },
  oil:            { matched: 'OIL',                     energy_kcal: 884, protein_g: 0,    carbs_g: 0,    fat_g: 100  },
  butter:         { matched: 'BUTTER',                  energy_kcal: 717, protein_g: 0.9,  carbs_g: 0.1,  fat_g: 81   },
  onion:          { matched: 'ONION (raw)',              energy_kcal: 40,  protein_g: 1.1,  carbs_g: 9.0,  fat_g: 0.1  },
  tomato:         { matched: 'TOMATO (raw)',             energy_kcal: 18,  protein_g: 0.9,  carbs_g: 3.9,  fat_g: 0.2  },
  carrot:         { matched: 'CARROT (raw)',             energy_kcal: 41,  protein_g: 0.9,  carbs_g: 10.0, fat_g: 0.2  },
  potato:         { matched: 'POTATO (boiled)',          energy_kcal: 77,  protein_g: 1.7,  carbs_g: 17.0, fat_g: 0.1  },
  lettuce:        { matched: 'LETTUCE (raw)',            energy_kcal: 15,  protein_g: 1.2,  carbs_g: 2.9,  fat_g: 0.2  },
  egg:            { matched: 'EGG',                     energy_kcal: 155, protein_g: 13.0, carbs_g: 1.1,  fat_g: 11.0 },
  eggs:           { matched: 'EGG',                     energy_kcal: 155, protein_g: 13.0, carbs_g: 1.1,  fat_g: 11.0 },
  milk:           { matched: 'MILK (whole)',             energy_kcal: 61,  protein_g: 3.2,  carbs_g: 4.8,  fat_g: 3.3  },
  salmon:         { matched: 'SALMON FILLET',            energy_kcal: 195, protein_g: 20.0, carbs_g: 0.0,  fat_g: 13.0 },
  chicken:        { matched: 'CHICKEN',                 energy_kcal: 165, protein_g: 25.0, carbs_g: 0.0,  fat_g: 7.0  },
  beef:           { matched: 'BEEF',                    energy_kcal: 250, protein_g: 26.0, carbs_g: 0.0,  fat_g: 15.0 },
  pork:           { matched: 'PORK',                    energy_kcal: 242, protein_g: 27.0, carbs_g: 0.0,  fat_g: 14.0 },
  rice:           { matched: 'RICE, COOKED',            energy_kcal: 130, protein_g: 2.7,  carbs_g: 28.0, fat_g: 0.3  },
  oat:            { matched: 'OAT FLAKES',              energy_kcal: 367, protein_g: 13.0, carbs_g: 56.0, fat_g: 7.0  },
  oats:           { matched: 'OAT FLAKES',              energy_kcal: 367, protein_g: 13.0, carbs_g: 56.0, fat_g: 7.0  },
  broccoli:       { matched: 'BROCCOLI',                energy_kcal: 34,  protein_g: 2.8,  carbs_g: 4.0,  fat_g: 0.4  },
  spinach:        { matched: 'SPINACH',                 energy_kcal: 23,  protein_g: 2.9,  carbs_g: 3.6,  fat_g: 0.4  },
  garlic:         { matched: 'GARLIC',                  energy_kcal: 149, protein_g: 6.4,  carbs_g: 33.0, fat_g: 0.5  },
  mushroom:       { matched: 'MUSHROOM',                energy_kcal: 22,  protein_g: 3.1,  carbs_g: 3.3,  fat_g: 0.3  },
  apple:          { matched: 'APPLE',                   energy_kcal: 52,  protein_g: 0.3,  carbs_g: 14.0, fat_g: 0.2  },
  banana:         { matched: 'BANANA',                  energy_kcal: 89,  protein_g: 1.1,  carbs_g: 23.0, fat_g: 0.3  },
  pasta:          { matched: 'PASTA, COOKED',           energy_kcal: 131, protein_g: 5.0,  carbs_g: 25.0, fat_g: 1.1  },
  bread:          { matched: 'BREAD, WHEAT',            energy_kcal: 265, protein_g: 9.0,  carbs_g: 49.0, fat_g: 3.5  },
  cheese:         { matched: 'CHEESE',                  energy_kcal: 402, protein_g: 25.0, carbs_g: 1.3,  fat_g: 33.0 },
  cream:          { matched: 'CREAM (heavy)',           energy_kcal: 337, protein_g: 2.5,  carbs_g: 2.9,  fat_g: 35.0 },
  yogurt:         { matched: 'YOGURT, PLAIN',           energy_kcal: 61,  protein_g: 3.5,  carbs_g: 4.7,  fat_g: 3.3  },
  yoghurt:        { matched: 'YOGURT, PLAIN',           energy_kcal: 61,  protein_g: 3.5,  carbs_g: 4.7,  fat_g: 3.3  },
  // Finnish
  vesi:           { matched: 'WATER',                   energy_kcal: 0,   protein_g: 0,    carbs_g: 0,    fat_g: 0    },
  suola:          { matched: 'SALT',                    energy_kcal: 0,   protein_g: 0,    carbs_g: 0,    fat_g: 0    },
  sokeri:         { matched: 'SUGAR',                   energy_kcal: 387, protein_g: 0,    carbs_g: 100,  fat_g: 0    },
  öljy:           { matched: 'OIL',                     energy_kcal: 884, protein_g: 0,    carbs_g: 0,    fat_g: 100  },
  voi:            { matched: 'BUTTER',                  energy_kcal: 717, protein_g: 0.9,  carbs_g: 0.1,  fat_g: 81   },
  sipuli:         { matched: 'ONION (raw)',              energy_kcal: 40,  protein_g: 1.1,  carbs_g: 9.0,  fat_g: 0.1  },
  tomaatti:       { matched: 'TOMATO (raw)',             energy_kcal: 18,  protein_g: 0.9,  carbs_g: 3.9,  fat_g: 0.2  },
  porkkana:       { matched: 'CARROT (raw)',             energy_kcal: 41,  protein_g: 0.9,  carbs_g: 10.0, fat_g: 0.2  },
  peruna:         { matched: 'POTATO (boiled)',          energy_kcal: 77,  protein_g: 1.7,  carbs_g: 17.0, fat_g: 0.1  },
  salaatti:       { matched: 'LETTUCE (raw)',            energy_kcal: 15,  protein_g: 1.2,  carbs_g: 2.9,  fat_g: 0.2  },
  kananmuna:      { matched: 'EGG',                     energy_kcal: 155, protein_g: 13.0, carbs_g: 1.1,  fat_g: 11.0 },
  maito:          { matched: 'MILK (whole)',             energy_kcal: 61,  protein_g: 3.2,  carbs_g: 4.8,  fat_g: 3.3  },
  lohi:           { matched: 'SALMON FILLET',            energy_kcal: 195, protein_g: 20.0, carbs_g: 0.0,  fat_g: 13.0 },
  lohifilee:      { matched: 'SALMON FILLET',            energy_kcal: 195, protein_g: 20.0, carbs_g: 0.0,  fat_g: 13.0 },
  riisi:          { matched: 'RICE, COOKED',            energy_kcal: 130, protein_g: 2.7,  carbs_g: 28.0, fat_g: 0.3  },
  kaura:          { matched: 'OAT FLAKES',              energy_kcal: 367, protein_g: 13.0, carbs_g: 56.0, fat_g: 7.0  },
  kaurahiutale:   { matched: 'OAT FLAKES',              energy_kcal: 367, protein_g: 13.0, carbs_g: 56.0, fat_g: 7.0  },
  parsakaali:     { matched: 'BROCCOLI',                energy_kcal: 34,  protein_g: 2.8,  carbs_g: 4.0,  fat_g: 0.4  },
  kana:           { matched: 'CHICKEN',                 energy_kcal: 165, protein_g: 25.0, carbs_g: 0.0,  fat_g: 7.0  },
  broileri:       { matched: 'CHICKEN',                 energy_kcal: 165, protein_g: 25.0, carbs_g: 0.0,  fat_g: 7.0  },
  naudanliha:     { matched: 'BEEF',                    energy_kcal: 250, protein_g: 26.0, carbs_g: 0.0,  fat_g: 15.0 },
  nauta:          { matched: 'BEEF',                    energy_kcal: 250, protein_g: 26.0, carbs_g: 0.0,  fat_g: 15.0 },
  sianliha:       { matched: 'PORK',                    energy_kcal: 242, protein_g: 27.0, carbs_g: 0.0,  fat_g: 14.0 },
  paprika:        { matched: 'BELL PEPPER',             energy_kcal: 26,  protein_g: 1.1,  carbs_g: 5.4,  fat_g: 0.3  },
  kurkku:         { matched: 'CUCUMBER',                energy_kcal: 12,  protein_g: 0.6,  carbs_g: 1.5,  fat_g: 0.1  },
  pinaatti:       { matched: 'SPINACH',                 energy_kcal: 23,  protein_g: 2.9,  carbs_g: 3.6,  fat_g: 0.4  },
  valkosipuli:    { matched: 'GARLIC',                  energy_kcal: 149, protein_g: 6.4,  carbs_g: 33.0, fat_g: 0.5  },
  sieni:          { matched: 'MUSHROOM',                energy_kcal: 22,  protein_g: 3.1,  carbs_g: 3.3,  fat_g: 0.3  },
  omena:          { matched: 'APPLE',                   energy_kcal: 52,  protein_g: 0.3,  carbs_g: 14.0, fat_g: 0.2  },
  banaani:        { matched: 'BANANA',                  energy_kcal: 89,  protein_g: 1.1,  carbs_g: 23.0, fat_g: 0.3  },
  makaroni:       { matched: 'MACARONI, COOKED',        energy_kcal: 131, protein_g: 5.0,  carbs_g: 25.0, fat_g: 1.1  },
  leipä:          { matched: 'BREAD, WHEAT',            energy_kcal: 265, protein_g: 9.0,  carbs_g: 49.0, fat_g: 3.5  },
  leipa:          { matched: 'BREAD, WHEAT',            energy_kcal: 265, protein_g: 9.0,  carbs_g: 49.0, fat_g: 3.5  },
  juusto:         { matched: 'CHEESE',                  energy_kcal: 402, protein_g: 25.0, carbs_g: 1.3,  fat_g: 33.0 },
  kerma:          { matched: 'CREAM (heavy)',           energy_kcal: 337, protein_g: 2.5,  carbs_g: 2.9,  fat_g: 35.0 },
  jogurtti:       { matched: 'YOGURT, PLAIN',           energy_kcal: 61,  protein_g: 3.5,  carbs_g: 4.7,  fat_g: 3.3  },
  makkara:        { matched: 'SAUSAGE',                 energy_kcal: 301, protein_g: 11.0, carbs_g: 5.0,  fat_g: 27.0 },
  liha:           { matched: 'BEEF (generic)',          energy_kcal: 250, protein_g: 26.0, carbs_g: 0.0,  fat_g: 15.0 },
  kala:           { matched: 'FISH',                    energy_kcal: 82,  protein_g: 18.0, carbs_g: 0.0,  fat_g: 1.0  },
  kanafilee:      { matched: 'CHICKEN FILLET',          energy_kcal: 110, protein_g: 23.0, carbs_g: 0.0,  fat_g: 1.5  },
  broilerifilee:  { matched: 'CHICKEN FILLET',          energy_kcal: 110, protein_g: 23.0, carbs_g: 0.0,  fat_g: 1.5  },
  jauheliha:      { matched: 'GROUND BEEF',             energy_kcal: 254, protein_g: 17.0, carbs_g: 0.0,  fat_g: 20.0 },
  tonnikala:      { matched: 'TUNA',                    energy_kcal: 132, protein_g: 29.0, carbs_g: 0.0,  fat_g: 1.0  },
  korppujauho:    { matched: 'BREADCRUMBS',             energy_kcal: 395, protein_g: 11.0, carbs_g: 75.0, fat_g: 3.5  },
  ranskankerma:   { matched: 'SOUR CREAM (crème fraîche)', energy_kcal: 292, protein_g: 2.5, carbs_g: 3.5, fat_g: 30.0 },
  piimä:          { matched: 'BUTTERMILK',              energy_kcal: 35,  protein_g: 3.1,  carbs_g: 4.4,  fat_g: 0.5  },
  täysjyväriisi:  { matched: 'BROWN RICE, COOKED',      energy_kcal: 123, protein_g: 2.6,  carbs_g: 26.0, fat_g: 1.0  },
  linssit:        { matched: 'LENTILS, COOKED',         energy_kcal: 116, protein_g: 9.0,  carbs_g: 20.0, fat_g: 0.4  },
  herneet:        { matched: 'PEAS, COOKED',            energy_kcal: 81,  protein_g: 5.0,  carbs_g: 14.0, fat_g: 0.4  },
  pavut:          { matched: 'BEANS, COOKED',           energy_kcal: 127, protein_g: 8.7,  carbs_g: 23.0, fat_g: 0.5  },
  kesäkurpitsa:   { matched: 'ZUCCHINI',                energy_kcal: 17,  protein_g: 1.2,  carbs_g: 3.1,  fat_g: 0.3  },
  mansikka:       { matched: 'STRAWBERRY',              energy_kcal: 33,  protein_g: 0.7,  carbs_g: 8.0,  fat_g: 0.3  },
  mustikka:       { matched: 'BLUEBERRY',               energy_kcal: 57,  protein_g: 0.7,  carbs_g: 14.0, fat_g: 0.3  },
  sitruuna:       { matched: 'LEMON',                   energy_kcal: 29,  protein_g: 1.1,  carbs_g: 9.3,  fat_g: 0.3  },
}

export const DEMO_RECIPES: DemoRecipe[] = [
  {
    name: 'Lihapullat',
    description: 'Finnish meatball mix — classic comfort food',
    servings: 4,
    ingredients: [
      { name: 'jauheliha', amount_g: 400 },
      { name: 'sipuli', amount_g: 80 },
      { name: 'kananmuna', amount_g: 60 },
      { name: 'korppujauho', amount_g: 30 },
      { name: 'maito', amount_g: 50 },
    ],
  },
  {
    name: 'Pasta Bolognese',
    description: 'Classic meat sauce with pasta',
    servings: 2,
    ingredients: [
      { name: 'pasta', amount_g: 200 },
      { name: 'jauheliha', amount_g: 300 },
      { name: 'tomaatti', amount_g: 200 },
      { name: 'sipuli', amount_g: 80 },
      { name: 'valkosipuli', amount_g: 10 },
      { name: 'öljy', amount_g: 15 },
    ],
  },
  {
    name: 'Kaurapuuro',
    description: 'Finnish oatmeal porridge with banana',
    servings: 1,
    ingredients: [
      { name: 'kaura', amount_g: 80 },
      { name: 'maito', amount_g: 300 },
      { name: 'banaani', amount_g: 120 },
    ],
  },
  {
    name: 'Broileri-riisipata',
    description: 'Chicken and rice casserole',
    servings: 3,
    ingredients: [
      { name: 'broileri', amount_g: 300 },
      { name: 'riisi', amount_g: 150 },
      { name: 'sipuli', amount_g: 80 },
      { name: 'porkkana', amount_g: 80 },
      { name: 'kerma', amount_g: 100 },
    ],
  },
]
